{"changed": true, "id": 4, "invocation": {"module_args": {"name": "******** vault", "description": "AAP ******** vault password (********)", "organization": "Default", "credential_type": "Vault", "inputs": {"vault_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "vault_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"}, "state": "present", "controller_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "controller_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "controller_host": "192.168.122.247", "validate_certs": false, "request_timeout": null, "controller_oauthtoken": null, "controller_config_file": null, "new_name": null, "copy_from": null, "user": null, "team": null}}, "warnings": ["You are running collection version 4.5.1 but connecting to Red Hat Ansible Automation Platform version 4.4.8", "The field inputs of credential 4 has encrypted data and may inaccurately report task is changed."]}